// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadFileData(arg1) {
  return window['go']['backend']['FileController']['LoadFileData'](arg1);
}

export function SelectFile() {
  return window['go']['backend']['FileController']['SelectFile']();
}

export function ShowMessage(arg1) {
  return window['go']['backend']['FileController']['ShowMessage'](arg1);
}
