// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {xls} from '../models';

export function LoadFileData(arg1:string):Promise<Array<xls.VehicleWorkbookStructure>>;

export function SelectFile():Promise<string>;

export function ShowMessage(arg1:string):Promise<Error>;
