// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
  return window['go']['backend']['TaskController']['AddTask'](arg1);
}

export function ChangeTaskStatus(arg1, arg2) {
  return window['go']['backend']['TaskController']['ChangeTaskStatus'](arg1, arg2);
}

export function GetTasks() {
  return window['go']['backend']['TaskController']['GetTasks']();
}

export function RemoveTask(arg1) {
  return window['go']['backend']['TaskController']['RemoveTask'](arg1);
}
