// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddTask(arg1:string):Promise<void>;

export function ChangeTaskStatus(arg1:string,arg2:boolean):Promise<void>;

export function GetTasks():Promise<Array<backend.Task>>;

export function RemoveTask(arg1:string):Promise<Error>;
