// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChangeTaskStatus(arg1:string,arg2:boolean):Promise<void>;

export function GetTasks():Promise<Array<main.ToDo>>;
