// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeTaskStatus(arg1, arg2) {
  return window['go']['main']['App']['ChangeTaskStatus'](arg1, arg2);
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}
